EntitySearch/EntitySearch.Demo.Web/Controllers/InventoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EntitySearch.Demo.Models;

namespace EntitySearch.Demo.Web.Controllers
{
    public class InventoriesController : Controller
    {
        private DemoDbContext db = new DemoDbContext();

        // GET: Inventories
        public ActionResult Index()
        {
            var inventories = db.Inventories.Include(i => i.Product).Include(i => i.Warehouse);
            return View(inventories.ToList());
        }

        // GET: Inventories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Inventory inventory = db.Inventories
                .Include(x => x.Product)
                .Include(x => x.Warehouse)
                .FirstOrDefault(x => x.InventoryId == id);
            if (inventory == null)
            {
                return HttpNotFound();
            }
            return View(inventory);
        }

        // GET: Inventories/Create
        public ActionResult Create()
        {
            ViewBag.ProductId = new SelectList(db.Products, "ProductId", "Manufacturer");
            ViewBag.WarehouseId = new SelectList(db.Warehouses, "WarehouseId", "Name");
            return View();
        }

        // POST: Inventories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "InventoryId,ProductId,Quantity,WarehouseId")] Inventory inventory)
        {
            if (ModelState.IsValid)
            {
                db.Inventories.Add(inventory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProductId = new SelectList(db.Products, "ProductId", "Manufacturer", inventory.ProductId);
            ViewBag.WarehouseId = new SelectList(db.Warehouses, "WarehouseId", "Name", inventory.WarehouseId);
            return View(inventory);
        }

        // GET: Inventories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Inventory inventory = db.Inventories.Find(id);
            if (inventory == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProductId = new SelectList(db.Products, "ProductId", "Manufacturer", inventory.ProductId);
            ViewBag.WarehouseId = new SelectList(db.Warehouses, "WarehouseId", "Name", inventory.WarehouseId);
            return View(inventory);
        }

        // POST: Inventories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "InventoryId,ProductId,Quantity,WarehouseId")] Inventory inventory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(inventory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProductId = new SelectList(db.Products, "ProductId", "Manufacturer", inventory.ProductId);
            ViewBag.WarehouseId = new SelectList(db.Warehouses, "WarehouseId", "Name", inventory.WarehouseId);
            return View(inventory);
        }

        // GET: Inventories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Inventory inventory = db.Inventories.Find(id);
            if (inventory == null)
            {
                return HttpNotFound();
            }
            return View(inventory);
        }

        // POST: Inventories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Inventory inventory = db.Inventories.Find(id);
            db.Inventories.Remove(inventory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EntitySearch/EntitySearch.Demo.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EntitySearch Demo: @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("EntitySearch Demo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>*@
                    <li>@Html.ActionLink("Inventory", "Index", "Inventories")</li>
                    <li>@Html.ActionLink("Customers", "Index", "Customers")</li>
                    <li>@Html.ActionLink("Orders", "Index", "Orders")</li>
                    <li class="visible-md visible-lg">@Html.ActionLink("Warehouses", "Index", "Warehouses")</li>
                    <li class="visible-md visible-lg">@Html.ActionLink("Products", "Index", "Products")</li>
                </ul>
                <form class="navbar-form navbar-left" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search" id="entity-search-in-nav" data-entity-search>
                    </div>
                </form>
                @*@Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year EntitySearch Demo App &bull; @Html.ActionLink("About", "About", "Home") &bull; @Html.ActionLink("Contact", "Contact", "Home")</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    @* EntitySearch: Set Route Data in the page to track this page as a recent. *@
    @{
        var routeValues = ViewContext.RouteData.Values.ToDictionary(x => x.Key, x => x.Value);
        // You will need to customize this if statement to configure which pages you want to be searchable.
        if (routeValues.ContainsKey("action")
            && (string)routeValues["action"] != "Edit"
            && (string)routeValues["action"] != "Create"
            && (string)routeValues["action"] != "Delete")
        {
            <script type="application/json" data-entity-search-route-data>@Html.Raw(Json.Encode(routeValues))</script>
        }
    }

    @* EntitySearch: Main javascript include for all pages in _Layout.cshtml. *@
    <script src=@Url.Content("~/Scripts/entity-search.js")></script>  
</body>
</html>